ACACIA_BOAT: 3

ACACIA_BUTTON: 3
ACACIA_CHEST_BOAT: 3
ACACIA_DOOR: 3
ACACIA_FENCE: 3
ACACIA_FENCE_GATE: 3
ACACIA_LEAVES: 3
ACACIA_LOG: 3
ACACIA_PLANKS: 3
ACACIA_PRESSURE_PLATE: 3
ACACIA_SAPLING: 3
ACACIA_SIGN: 3
ACACIA_SLAB: 3
ACACIA_STAIRS: 3
ACACIA_TRAPDOOR: 3
ACACIA_WALL_SIGN: 3
ACACIA_WOOD: 3
AMETHYST_BLOCK: 7
AMETHYST_CLUSTER: 7
AMETHYST_SHARD: 7
ANCIENT_DEBRIS: 10
ANDESITE: 7
ANDESITE_SLAB: 7
ANDESITE_STAIRS: 7
ANDESITE_WALL: 7
ANVIL: 100
AXOLOTL_BUCKET: 7
BARREL: 4
BASALT: 7
BEACON: 200
BEDROCK: 7
BEE_NEST: 4
BEEHIVE: 4
BELL: 7
BIRCH_BOAT: 3
BIRCH_BUTTON: 3
BIRCH_CHEST_BOAT: 3
BIRCH_DOOR: 3
BIRCH_FENCE: 3
BIRCH_FENCE_GATE: 3
BIRCH_LEAVES: 3
BIRCH_LOG: 3
BIRCH_PLANKS: 3
BIRCH_PRESSURE_PLATE: 3
BIRCH_SAPLING: 3
BIRCH_SIGN: 3
BIRCH_SLAB: 3
BIRCH_STAIRS: 3
BIRCH_TRAPDOOR: 3
BIRCH_WALL_SIGN: 3
BIRCH_WOOD: 3
BLACK_BED: 7
BLACK_CONCRETE: 7
BLACK_CONCRETE_POWDER: 7
BLACK_GLAZED_TERRACOTTA: 7
BLACK_SHULKER_BOX: 3
BLACK_STAINED_GLASS: 3
BLACK_STAINED_GLASS_PANE: 1
BLACK_TERRACOTTA: 7
BLACK_WOOL: 2
BLACKSTONE: 7
BLACKSTONE_SLAB: 7
BLACKSTONE_STAIRS: 7
BLACKSTONE_WALL: 7
BLAST_FURNACE: 7
BLUE_BED: 7
BLUE_CONCRETE: 7
BLUE_CONCRETE_POWDER: 7
BLUE_GLAZED_TERRACOTTA: 7
BLUE_ICE: 7
BLUE_SHULKER_BOX: 3
BLUE_STAINED_GLASS: 3
BLUE_STAINED_GLASS_PANE: 1
BLUE_TERRACOTTA: 7
BLUE_WOOL: 2
BONE_BLOCK: 5
BOOKSHELF: 3
BRAIN_CORAL_BLOCK: 3
BREWING_STAND: 5
BRICK: 7
BRICK_SLAB: 7
BRICK_STAIRS: 7
BRICK_WALL: 7
BRICKS: 7
BROWN_BED: 7
BROWN_CONCRETE: 7
BROWN_CONCRETE_POWDER: 7
BROWN_GLAZED_TERRACOTTA: 7
BROWN_MUSHROOM_BLOCK: 3
BROWN_SHULKER_BOX: 3
BROWN_STAINED_GLASS: 3
BROWN_STAINED_GLASS_PANE: 1
BROWN_TERRACOTTA: 7
BROWN_WOOL: 2
BUBBLE_CORAL_BLOCK: 3
BUCKET: 7
BUDDING_AMETHYST: 7
CALCITE: 7
CAMPFIRE: 3
CARTOGRAPHY_TABLE: 4
CARVED_PUMPKIN: 3
CAULDRON: 7
CHAIN: 10
CHAINMAIL_BOOTS: 100
CHAINMAIL_CHESTPLATE: 300
CHAINMAIL_HELMET: 200
CHAINMAIL_LEGGINGS: 200
CHEST: 4
CHEST_MINECART: 5
CHIPPED_ANVIL: 100
CHISELED_DEEPSLATE: 7
CHISELED_NETHER_BRICKS: 7
CHISELED_POLISHED_BLACKSTONE: 7
CHISELED_QUARTZ_BLOCK: 7
CHISELED_RED_SANDSTONE: 7
CHISELED_SANDSTONE: 7
CHISELED_STONE_BRICKS: 7
CLAY: 5
COAL_BLOCK: 9
COAL_ORE: 7
COARSE_DIRT: 5
COBBLED_DEEPSLATE: 7
COBBLED_DEEPSLATE_SLAB: 7
COBBLED_DEEPSLATE_STAIRS: 7
COBBLED_DEEPSLATE_WALL: 7
COBBLESTONE: 7
COBBLESTONE_SLAB: 7
COBBLESTONE_STAIRS: 7
COBBLESTONE_WALL: 7
COD_BUCKET: 7
COPPER_BLOCK: 7
COPPER_INGOT: 7
COPPER_ORE: 7
CRACKED_DEEPSLATE_BRICKS: 7
CRACKED_DEEPSLATE_TILES: 7
CRACKED_NETHER_BRICKS: 7
CRACKED_POLISHED_BLACKSTONE_BRICKS: 7
CRACKED_STONE_BRICKS: 7
CRAFTING_TABLE: 4
CRIMSON_BUTTON: 3
CRIMSON_DOOR: 3
CRIMSON_FENCE: 3
CRIMSON_FENCE_GATE: 3
CRIMSON_FUNGUS: 3
CRIMSON_HYPHAE: 3
CRIMSON_NYLIUM: 3
CRIMSON_PLANKS: 3
CRIMSON_PRESSURE_PLATE: 3
CRIMSON_ROOTS: 3
CRIMSON_SIGN: 3
CRIMSON_SLAB: 3
CRIMSON_STAIRS: 3
CRIMSON_STEM: 3
CRIMSON_TRAPDOOR: 3
CRIMSON_WALL_SIGN: 3
CRYING_OBSIDIAN: 50
CUT_COPPER: 7
CUT_COPPER_SLAB: 7
CUT_COPPER_STAIRS: 7
CUT_RED_SANDSTONE: 7
CUT_RED_SANDSTONE_SLAB: 7
CUT_SANDSTONE: 7
CUT_SANDSTONE_SLAB: 7
CYAN_BED: 7
CYAN_CONCRETE: 7
CYAN_CONCRETE_POWDER: 7
CYAN_GLAZED_TERRACOTTA: 7
CYAN_SHULKER_BOX: 3
CYAN_STAINED_GLASS: 3
CYAN_STAINED_GLASS_PANE: 1
CYAN_TERRACOTTA: 7
CYAN_WOOL: 2
DAMAGED_ANVIL: 100
DARK_OAK_BOAT: 3
DARK_OAK_BUTTON: 3
DARK_OAK_CHEST_BOAT: 3
DARK_OAK_DOOR: 3
DARK_OAK_FENCE: 3
DARK_OAK_FENCE_GATE: 3
DARK_OAK_LEAVES: 3
DARK_OAK_LOG: 3
DARK_OAK_PLANKS: 3
DARK_OAK_PRESSURE_PLATE: 3
DARK_OAK_SAPLING: 3
DARK_OAK_SIGN: 3
DARK_OAK_SLAB: 3
DARK_OAK_STAIRS: 3
DARK_OAK_TRAPDOOR: 3
DARK_OAK_WALL_SIGN: 3
DARK_OAK_WOOD: 3
DARK_PRISMARINE: 7
DARK_PRISMARINE_SLAB: 7
DARK_PRISMARINE_STAIRS: 7
DEAD_BRAIN_CORAL_BLOCK: 3
DEAD_BUBBLE_CORAL_BLOCK: 3
DEAD_FIRE_CORAL_BLOCK: 3
DEAD_HORN_CORAL_BLOCK: 3
DEAD_TUBE_CORAL_BLOCK: 3
DEEPSLATE: 7
DEEPSLATE_BRICK_SLAB: 7
DEEPSLATE_BRICK_STAIRS: 7
DEEPSLATE_BRICK_WALL: 7
DEEPSLATE_BRICKS: 7
DEEPSLATE_COAL_ORE: 7
DEEPSLATE_COPPER_ORE: 7
DEEPSLATE_DIAMOND_ORE: 7
DEEPSLATE_EMERALD_ORE: 7
DEEPSLATE_GOLD_ORE: 7
DEEPSLATE_IRON_ORE: 7
DEEPSLATE_LAPIS_ORE: 7
DEEPSLATE_REDSTONE_ORE: 7
DEEPSLATE_TILE_SLAB: 7
DEEPSLATE_TILE_STAIRS: 7
DEEPSLATE_TILE_WALL: 7
DEEPSLATE_TILES: 7
DIAMOND: 5
DIAMOND_AXE: 50
DIAMOND_BLOCK: 45
DIAMOND_BOOTS: 100
DIAMOND_CHESTPLATE: 300
DIAMOND_HELMET: 200
DIAMOND_HOE: 50
DIAMOND_HORSE_ARMOR: 5
DIAMOND_LEGGINGS: 200
DIAMOND_ORE: 12
DIAMOND_PICKAXE: 50
DIAMOND_SHOVEL: 50
DIAMOND_SWORD: 50
DIORITE: 7
DIORITE_SLAB: 7
DIORITE_STAIRS: 7
DIORITE_WALL: 7
DIRT: 5
DIRT_PATH: 5
DISPENSER: 5
DRAGON_EGG: 1000
DRIPSTONE_BLOCK: 7
DROPPER: 5
EMERALD_BLOCK: 9
EMERALD_ORE: 7
ENCHANTED_GOLDEN_APPLE: 900
ENCHANTING_TABLE: 50
END_STONE: 7
END_STONE_BRICK_SLAB: 7
END_STONE_BRICK_STAIRS: 7
END_STONE_BRICK_WALL: 7
END_STONE_BRICKS: 7
ENDER_CHEST: 50
ENDER_PEARL: 4
EXPOSED_COPPER: 7
EXPOSED_CUT_COPPER: 7
EXPOSED_CUT_COPPER_SLAB: 7
EXPOSED_CUT_COPPER_STAIRS: 7
FARMLAND: 5
FEATHER: -50
FIRE_CORAL_BLOCK: 3
FLETCHING_TABLE: 4
FROSTED_ICE: 7
FURNACE: 7
FURNACE_MINECART: 12
GILDED_BLACKSTONE: 7
GLASS: 3
GLASS_BOTTLE: 3
GLASS_PANE: 1
GLOWSTONE: 7
GLOWSTONE_DUST: 7
GOLD_BLOCK: 81
GOLD_INGOT: 9
GOLD_NUGGET: 1
GOLD_ORE: 19
GOLDEN_APPLE: 19
GOLDEN_AXE: 50
GOLDEN_BOOTS: 100
GOLDEN_CHESTPLATE: 300
GOLDEN_HELMET: 200
GOLDEN_HOE: 5
GOLDEN_HORSE_ARMOR: 5
GOLDEN_LEGGINGS: 200
GOLDEN_PICKAXE: 50
GOLDEN_SHOVEL: 50
GOLDEN_SWORD: 50
GRANITE: 7
GRANITE_SLAB: 7
GRANITE_STAIRS: 7
GRANITE_WALL: 7
GRASS_BLOCK: 5
GRAVEL: 5
GRAY_BED: 7
GRAY_CONCRETE: 7
GRAY_CONCRETE_POWDER: 7
GRAY_GLAZED_TERRACOTTA: 7
GRAY_SHULKER_BOX: 3
GRAY_STAINED_GLASS: 3
GRAY_STAINED_GLASS_PANE: 1
GRAY_TERRACOTTA: 7
GRAY_WOOL: 2
GREEN_BED: 7
GREEN_CONCRETE: 7
GREEN_CONCRETE_POWDER: 7
GREEN_GLAZED_TERRACOTTA: 7
GREEN_SHULKER_BOX: 3
GREEN_STAINED_GLASS: 3
GREEN_STAINED_GLASS_PANE: 1
GREEN_TERRACOTTA: 7
GREEN_WOOL: 2
GRINDSTONE: 7
HAY_BLOCK: 9
HONEY_BLOCK: 4
HONEYCOMB: 4
HONEYCOMB_BLOCK: 4
HOPPER: 40
HOPPER_MINECART: 50
HORN_CORAL_BLOCK: 3
ICE: 7
INFESTED_CHISELED_STONE_BRICKS: 7
INFESTED_COBBLESTONE: 7
INFESTED_CRACKED_STONE_BRICKS: 7
INFESTED_DEEPSLATE: 7
INFESTED_MOSSY_STONE_BRICKS: 7
INFESTED_STONE: 7
INFESTED_STONE_BRICKS: 7
IRON_AXE: 50
IRON_BARS: 4
IRON_BLOCK: 81
IRON_BOOTS: 100
IRON_CHESTPLATE: 300
IRON_DOOR: 5
IRON_HELMET: 200
IRON_HOE: 50
IRON_HORSE_ARMOR: 5
IRON_INGOT: 9
IRON_LEGGINGS: 200
IRON_NUGGET: 1
IRON_ORE: 50
IRON_PICKAXE: 50
IRON_SHOVEL: 50
IRON_SWORD: 50
IRON_TRAPDOOR: 5
JACK_O_LANTERN: 5
JUKEBOX: 3
JUNGLE_BOAT: 3
JUNGLE_BUTTON: 3
JUNGLE_CHEST_BOAT: 3
JUNGLE_DOOR: 3
JUNGLE_FENCE: 3
JUNGLE_FENCE_GATE: 3
JUNGLE_LEAVES: 3
JUNGLE_LOG: 3
JUNGLE_PLANKS: 3
JUNGLE_PRESSURE_PLATE: 3
JUNGLE_SAPLING: 3
JUNGLE_SIGN: 3
JUNGLE_SLAB: 3
JUNGLE_STAIRS: 3
JUNGLE_TRAPDOOR: 3
JUNGLE_WALL_SIGN: 3
JUNGLE_WOOD: 3
LADDER: 4
LANTERN: 6
LAPIS_BLOCK: 45
LAPIS_LAZULI: 5
LAPIS_ORE: 15
LARGE_AMETHYST_BUD: 10
LAVA_BUCKET: 7
LEATHER_BOOTS: 10
LEATHER_CHESTPLATE: 20
LEATHER_HELMET: 10
LEATHER_HORSE_ARMOR: 5
LEATHER_LEGGINGS: 10
LECTERN: 5
LIGHT_BLUE_BED: 7
LIGHT_BLUE_CONCRETE: 7
LIGHT_BLUE_CONCRETE_POWDER: 7
LIGHT_BLUE_GLAZED_TERRACOTTA: 7
LIGHT_BLUE_SHULKER_BOX: 3
LIGHT_BLUE_STAINED_GLASS: 3
LIGHT_BLUE_STAINED_GLASS_PANE: 1
LIGHT_BLUE_TERRACOTTA: 7
LIGHT_BLUE_WOOL: 2
LIGHT_GRAY_BED: 7
LIGHT_GRAY_CONCRETE: 7
LIGHT_GRAY_CONCRETE_POWDER: 7
LIGHT_GRAY_GLAZED_TERRACOTTA: 7
LIGHT_GRAY_SHULKER_BOX: 3
LIGHT_GRAY_STAINED_GLASS: 3
LIGHT_GRAY_STAINED_GLASS_PANE: 1
LIGHT_GRAY_TERRACOTTA: 7
LIGHT_GRAY_WOOL: 2
LIME_BED: 7
LIME_CONCRETE: 7
LIME_CONCRETE_POWDER: 7
LIME_GLAZED_TERRACOTTA: 7
LIME_SHULKER_BOX: 3
LIME_STAINED_GLASS: 3
LIME_STAINED_GLASS_PANE: 1
LIME_TERRACOTTA: 7
LIME_WOOL: 2
LODESTONE: 7
LOOM: 4
MAGENTA_BED: 7
MAGENTA_CONCRETE: 7
MAGENTA_CONCRETE_POWDER: 7
MAGENTA_GLAZED_TERRACOTTA: 7
MAGENTA_SHULKER_BOX: 3
MAGENTA_STAINED_GLASS: 3
MAGENTA_STAINED_GLASS_PANE: 1
MAGENTA_TERRACOTTA: 7
MAGENTA_WOOL: 2
MAGMA_BLOCK: 3
MANGROVE_BOAT: 3
MANGROVE_BUTTON: 3
MANGROVE_CHEST_BOAT: 3
MANGROVE_DOOR: 3
MANGROVE_FENCE: 3
MANGROVE_FENCE_GATE: 3
MANGROVE_LEAVES: 3
MANGROVE_LOG: 3
MANGROVE_PLANKS: 3
MANGROVE_PRESSURE_PLATE: 3
MANGROVE_PROPAGULE: 3
MANGROVE_ROOTS: 3
MANGROVE_SIGN: 3
MANGROVE_SLAB: 3
MANGROVE_STAIRS: 3
MANGROVE_TRAPDOOR: 3
MANGROVE_WALL_SIGN: 3
MANGROVE_WOOD: 3
MEDIUM_AMETHYST_BUD: 5
MELON: 5
MILK_BUCKET: 7
MINECART: 40
MOSSY_COBBLESTONE: 7
MOSSY_COBBLESTONE_SLAB: 7
MOSSY_COBBLESTONE_STAIRS: 7
MOSSY_COBBLESTONE_WALL: 7
MOSSY_STONE_BRICK_SLAB: 7
MOSSY_STONE_BRICK_STAIRS: 7
MOSSY_STONE_BRICK_WALL: 7
MOSSY_STONE_BRICKS: 7
MUD: 5
MUD_BRICK_SLAB: 7
MUD_BRICK_STAIRS: 7
MUD_BRICK_WALL: 7
MUD_BRICKS: 7
MUDDY_MANGROVE_ROOTS: 3
MUSHROOM_STEM: 4
MYCELIUM: 5
NETHER_BRICK: 7
NETHER_BRICK_FENCE: 7
NETHER_BRICK_SLAB: 7
NETHER_BRICK_STAIRS: 7
NETHER_BRICK_WALL: 7
NETHER_BRICKS: 7
NETHER_GOLD_ORE: 10
NETHER_QUARTZ_ORE: 7
NETHER_STAR: 300
NETHER_WART_BLOCK: 5
NETHERITE_AXE: 100
NETHERITE_BLOCK: 100
NETHERITE_BOOTS: 100
NETHERITE_CHESTPLATE: 400
NETHERITE_HELMET: 200
NETHERITE_HOE: 100
NETHERITE_INGOT: 50
NETHERITE_LEGGINGS: 200
NETHERITE_PICKAXE: 100
NETHERITE_SCRAP: 10
NETHERITE_SHOVEL: 100
NETHERITE_SWORD: 100
NETHERRACK: 2
NOTE_BLOCK: 4
OAK_BOAT: 3
OAK_BUTTON: 3
OAK_CHEST_BOAT: 3
OAK_DOOR: 3
OAK_FENCE: 3
OAK_FENCE_GATE: 3
OAK_LEAVES: 3
OAK_LOG: 3
OAK_PLANKS: 3
OAK_PRESSURE_PLATE: 3
OAK_SAPLING: 3
OAK_SIGN: 3
OAK_SLAB: 3
OAK_STAIRS: 3
OAK_TRAPDOOR: 3
OAK_WALL_SIGN: 3
OAK_WOOD: 3
OBSERVER: 7
OBSIDIAN: 50
OCHRE_FROGLIGHT: 3
ORANGE_BED: 7
ORANGE_CONCRETE: 7
ORANGE_CONCRETE_POWDER: 7
ORANGE_GLAZED_TERRACOTTA: 7
ORANGE_SHULKER_BOX: 3
ORANGE_STAINED_GLASS: 3
ORANGE_STAINED_GLASS_PANE: 1
ORANGE_TERRACOTTA: 7
ORANGE_WOOL: 2
OXIDIZED_COPPER: 7
OXIDIZED_CUT_COPPER: 7
OXIDIZED_CUT_COPPER_SLAB: 7
OXIDIZED_CUT_COPPER_STAIRS: 7
PACKED_ICE: 3
PACKED_MUD: 5
PEARLESCENT_FROGLIGHT: 3
PETRIFIED_OAK_SLAB: 3
PINK_BED: 7
PINK_CONCRETE: 7
PINK_CONCRETE_POWDER: 7
PINK_GLAZED_TERRACOTTA: 7
PINK_SHULKER_BOX: 3
PINK_STAINED_GLASS: 3
PINK_STAINED_GLASS_PANE: 1
PINK_TERRACOTTA: 7
PINK_WOOL: 2
PISTON: 6
PODZOL: 5
POINTED_DRIPSTONE: 7
POLISHED_ANDESITE: 7
POLISHED_ANDESITE_SLAB: 7
POLISHED_ANDESITE_STAIRS: 7
POLISHED_BASALT:
POLISHED_BLACKSTONE: 7
POLISHED_BLACKSTONE_BRICK_SLAB: 7
POLISHED_BLACKSTONE_BRICK_STAIRS: 7
POLISHED_BLACKSTONE_BRICK_WALL: 7
POLISHED_BLACKSTONE_BRICKS: 7
POLISHED_BLACKSTONE_BUTTON: 7
POLISHED_BLACKSTONE_PRESSURE_PLATE: 7
POLISHED_BLACKSTONE_SLAB: 7
POLISHED_BLACKSTONE_STAIRS: 7
POLISHED_BLACKSTONE_WALL: 7
POLISHED_DEEPSLATE: 7
POLISHED_DEEPSLATE_SLAB: 7
POLISHED_DEEPSLATE_STAIRS: 7
POLISHED_DEEPSLATE_WALL: 7
POLISHED_DIORITE: 7
POLISHED_DIORITE_SLAB: 7
POLISHED_DIORITE_STAIRS: 7
POLISHED_GRANITE: 7
POLISHED_GRANITE_SLAB: 7
POLISHED_GRANITE_STAIRS: 7
POWDER_SNOW: 10
POWDER_SNOW_BUCKET: 7
POWDER_SNOW_CAULDRON: 50
PRISMARINE: 7
PRISMARINE_BRICK_SLAB: 7
PRISMARINE_BRICK_STAIRS: 7
PRISMARINE_BRICKS: 7
PRISMARINE_CRYSTALS: 7
PRISMARINE_SHARD: 7
PRISMARINE_SLAB: 7
PRISMARINE_STAIRS: 7
PRISMARINE_WALL: 7
PUFFERFISH_BUCKET: 7
PUMPKIN: 5
PURPLE_BED: 7
PURPLE_CONCRETE: 7
PURPLE_CONCRETE_POWDER: 7
PURPLE_GLAZED_TERRACOTTA: 7
PURPLE_SHULKER_BOX: 3
PURPLE_STAINED_GLASS: 3
PURPLE_STAINED_GLASS_PANE: 1
PURPLE_TERRACOTTA: 7
PURPLE_WOOL: 2
PURPUR_BLOCK: 7
PURPUR_PILLAR: 7
PURPUR_SLAB: 7
PURPUR_STAIRS: 7
QUARTZ: 7
QUARTZ_BLOCK: 7
QUARTZ_BRICKS: 7
QUARTZ_PILLAR: 7
QUARTZ_SLAB: 7
QUARTZ_STAIRS: 7
RAW_COPPER: 7
RAW_COPPER_BLOCK: 7
RAW_GOLD: 9
RAW_GOLD_BLOCK: 81
RAW_IRON: 9
RAW_IRON_BLOCK: 81
RED_BED: 7
RED_CONCRETE: 7
RED_CONCRETE_POWDER: 7
RED_GLAZED_TERRACOTTA: 7
RED_MUSHROOM_BLOCK: 5
RED_NETHER_BRICK_SLAB: 7
RED_NETHER_BRICK_STAIRS: 7
RED_NETHER_BRICK_WALL: 7
RED_NETHER_BRICKS: 7
RED_SAND: 5
RED_SANDSTONE: 7
RED_SANDSTONE_SLAB: 7
RED_SANDSTONE_STAIRS: 7
RED_SANDSTONE_WALL: 7
RED_SHULKER_BOX: 3
RED_STAINED_GLASS: 3
RED_STAINED_GLASS_PANE: 1
RED_TERRACOTTA: 7
RED_WOOL: 2
REDSTONE: 7
REDSTONE_BLOCK: 7
REDSTONE_LAMP: 7
REDSTONE_ORE: 7
REDSTONE_TORCH: 7
REDSTONE_WALL_TORCH: 7
REDSTONE_WIRE: 7
REINFORCED_DEEPSLATE: 7
REPEATER: 7
ROOTED_DIRT: 5
SALMON_BUCKET: 7
SAND: 5
SANDSTONE: 7
SANDSTONE_SLAB: 7
SANDSTONE_STAIRS: 7
SANDSTONE_WALL: 7
SCAFFOLDING: 3
SCULK: 5
SCULK_CATALYST: 5
SCULK_SENSOR: 5
SCULK_SHRIEKER: 5
SCUTE: 5
SEA_LANTERN: 5
SHIELD: 100
SHROOMLIGHT: 5
SHULKER_BOX: 3
SLIME_BLOCK: 10
SMALL_AMETHYST_BUD: 10
SMITHING_TABLE: 7
SMOKER: 7
SMOOTH_BASALT: 7
SMOOTH_QUARTZ: 7
SMOOTH_QUARTZ_SLAB: 7
SMOOTH_QUARTZ_STAIRS: 7
SMOOTH_RED_SANDSTONE: 7
SMOOTH_RED_SANDSTONE_SLAB: 7
SMOOTH_RED_SANDSTONE_STAIRS: 7
SMOOTH_SANDSTONE: 7
SMOOTH_SANDSTONE_SLAB: 7
SMOOTH_SANDSTONE_STAIRS: 7
SMOOTH_STONE: 7
SMOOTH_STONE_SLAB: 7
SNOW_BLOCK: 4
SOUL_CAMPFIRE: 4
SOUL_LANTERN: 5
SOUL_SAND: 5
SOUL_SOIL: 5
SPONGE: 4
SPRUCE_BOAT: 3
SPRUCE_BUTTON: 3
SPRUCE_CHEST_BOAT: 3
SPRUCE_DOOR: 3
SPRUCE_FENCE: 3
SPRUCE_FENCE_GATE: 3
SPRUCE_LEAVES: 3
SPRUCE_LOG: 3
SPRUCE_PLANKS: 3
SPRUCE_PRESSURE_PLATE: 3
SPRUCE_SAPLING: 3
SPRUCE_SIGN: 3
SPRUCE_SLAB: 3
SPRUCE_STAIRS: 3
SPRUCE_TRAPDOOR: 3
SPRUCE_WALL_SIGN: 3
SPRUCE_WOOD: 3
SPYGLASS: 3
STICKY_PISTON: 5
STONE: 7
STONE_AXE: 7
STONE_BRICK_SLAB: 7
STONE_BRICK_STAIRS: 7
STONE_BRICK_WALL: 7
STONE_BRICKS: 7
STONE_BUTTON: 7
STONE_HOE: 7
STONE_PICKAXE: 7
STONE_PRESSURE_PLATE: 7
STONE_SHOVEL: 7
STONE_SLAB: 7
STONE_STAIRS: 7
STONE_SWORD: 7
STONECUTTER: 7
STRIPPED_ACACIA_LOG: 3
STRIPPED_ACACIA_WOOD: 3
STRIPPED_BIRCH_LOG: 3
STRIPPED_BIRCH_WOOD: 3
STRIPPED_CRIMSON_HYPHAE: 3
STRIPPED_CRIMSON_STEM: 3
STRIPPED_DARK_OAK_LOG: 3
STRIPPED_DARK_OAK_WOOD: 3
STRIPPED_JUNGLE_LOG: 3
STRIPPED_JUNGLE_WOOD: 3
STRIPPED_MANGROVE_LOG: 3
STRIPPED_MANGROVE_WOOD: 3
STRIPPED_OAK_LOG: 3
STRIPPED_OAK_WOOD: 3
STRIPPED_SPRUCE_LOG: 3
STRIPPED_SPRUCE_WOOD: 3
STRIPPED_WARPED_HYPHAE: 3
STRIPPED_WARPED_STEM: 3
TADPOLE_BUCKET: 7
TARGET: 5
TERRACOTTA: 7
TINTED_GLASS: 3
TNT_MINECART: 5
TOTEM_OF_UNDYING: 100
TRAPPED_CHEST: 4
TRIDENT: 4
TROPICAL_FISH_BUCKET: 7
TUBE_CORAL_BLOCK: 3
TUFF: 7
TURTLE_HELMET: 50
VERDANT_FROGLIGHT: 3
WARPED_BUTTON: 3
WARPED_DOOR: 3
WARPED_FENCE: 3
WARPED_FENCE_GATE: 3
WARPED_FUNGUS: 3
WARPED_FUNGUS_ON_A_STICK: 3
WARPED_HYPHAE: 3
WARPED_NYLIUM: 3
WARPED_PLANKS: 3
WARPED_PRESSURE_PLATE: 3
WARPED_ROOTS: 3
WARPED_SIGN: 3
WARPED_SLAB: 3
WARPED_STAIRS: 3
WARPED_STEM: 3
WARPED_TRAPDOOR: 3
WARPED_WALL_SIGN: 3
WARPED_WART_BLOCK: 3
WATER_BUCKET: 7
WATER_CAULDRON: 10
WAXED_COPPER_BLOCK: 7
WAXED_CUT_COPPER: 7
WAXED_CUT_COPPER_SLAB: 7
WAXED_CUT_COPPER_STAIRS: 7
WAXED_EXPOSED_COPPER: 7
WAXED_EXPOSED_CUT_COPPER: 7
WAXED_EXPOSED_CUT_COPPER_SLAB: 7
WAXED_EXPOSED_CUT_COPPER_STAIRS: 7
WAXED_OXIDIZED_COPPER: 7
WAXED_OXIDIZED_CUT_COPPER: 7
WAXED_OXIDIZED_CUT_COPPER_SLAB: 7
WAXED_OXIDIZED_CUT_COPPER_STAIRS: 7
WAXED_WEATHERED_COPPER: 7
WAXED_WEATHERED_CUT_COPPER: 7
WAXED_WEATHERED_CUT_COPPER_SLAB: 7
WAXED_WEATHERED_CUT_COPPER_STAIRS: 7
WEATHERED_COPPER: 7
WEATHERED_CUT_COPPER: 7
WEATHERED_CUT_COPPER_SLAB: 7
WEATHERED_CUT_COPPER_STAIRS: 7
WHITE_BED: 7
WHITE_CONCRETE: 7
WHITE_CONCRETE_POWDER: 7
WHITE_GLAZED_TERRACOTTA: 7
WHITE_SHULKER_BOX: 3
WHITE_STAINED_GLASS: 3
WHITE_STAINED_GLASS_PANE: 1
WHITE_TERRACOTTA: 7
WHITE_WOOL: 2
WOODEN_AXE: 50
WOODEN_HOE: 50
WOODEN_PICKAXE: 50
WOODEN_SHOVEL: 50
WOODEN_SWORD: 50
YELLOW_BED: 7
YELLOW_CONCRETE: 7
YELLOW_CONCRETE_POWDER: 7
YELLOW_GLAZED_TERRACOTTA: 7
YELLOW_SHULKER_BOX: 3
YELLOW_STAINED_GLASS: 3
YELLOW_STAINED_GLASS_PANE: 1
YELLOW_TERRACOTTA: 7
YELLOW_WOOL: 2
